name: Build.Validate

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "tests/**"
      - "package-lock.json"
      - "package.json"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
      - "tests/**"
      - "package-lock.json"
      - "package.json"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  # 1. Lint GitHub Actions / YAML
  lint-actions:
    name: Lint.Actions
    uses: ./.github/workflows/_Validate.Lint.Actions.yaml

  # 2. Validate PR Title (Conventional Commit)
  lint-pr:
    name: Lint.PR
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/_Validate.Lint.PR.yaml

  # 3. Node Build + Sonar Scan + Docker Build Validation
  node-build:
    name: Node.Build
    needs: [lint-actions, lint-pr]
    if: ${{ (github.event_name != 'pull_request' || needs.lint-pr.result == 'success') && needs.lint-actions.result == 'success' }}
    uses: ./.github/workflows/Node.Build.Validate.yaml
    with:
      node_version: 20
      project_root_directory: "."
      npmscripts: lint,typecheck,format:check
      run_sonar_scan: true

  # 4. Jest Tests (E2E)
  jest:
    name: Jest.Unit.Test
    needs: [node-build]
    if: ${{needs.node-build.result == 'success'}}
    uses: ./.github/workflows/jest.yaml
